name: supply_chain_py311
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.12=h4ab18f5_0
  - anyio=4.6.2=py312h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_1
  - asttokens=3.0.0=py312h06a4308_0
  - async-lru=2.0.4=py312h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.3.0=py312h06a4308_0
  - babel=2.16.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - bleach=6.2.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.18.0=hbb29018_2
  - certifi=2025.1.31=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py312h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h267a509_2
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glib=2.80.3=h315aac3_2
  - glib-tools=2.80.3=h8fdd7da_2
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.6=hbaaba92_0
  - gstreamer=1.24.6=haf2f30d_0
  - h11=0.14.0=py312h06a4308_0
  - harfbuzz=9.0.0=hfac3d4d_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - icu=73.2=h59595ed_0
  - idna=3.7=py312h06a4308_0
  - ipykernel=6.29.5=py312h06a4308_1
  - ipython=8.30.0=py312h06a4308_0
  - ipywidgets=8.1.5=py312h06a4308_0
  - jedi=0.19.2=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - json5=0.9.25=py312h06a4308_0
  - jsonschema=4.23.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter=1.1.1=py312h06a4308_0
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.3=py312h06a4308_0
  - jupyter_console=6.6.3=py312h06a4308_1
  - jupyter_core=5.7.2=py312h06a4308_0
  - jupyter_events=0.12.0=py312h06a4308_0
  - jupyter_server=2.15.0=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.3.4=py312h06a4308_0
  - jupyterlab_pygments=0.3.0=py312h06a4308_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - jupyterlab_widgets=3.0.13=py312h06a4308_0
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libcap=2.69=h0f662aa_0
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=18.1.8=default_h9def88c_2
  - libcups=2.3.3=h4637d8d_4
  - libedit=3.1.20230828=h5eee18b_0
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=13.2.0=h77fa898_12
  - libgcrypt=1.11.0=h4ab18f5_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libglib=2.80.3=h315aac3_2
  - libgomp=13.2.0=h77fa898_12
  - libgpg-error=1.51=h5eee18b_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.8=h8b73ec9_2
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.43=h2797004_0
  - libpq=16.4=h482b261_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_12
  - libsystemd0=256.5=hb6d7363_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=hd590300_0
  - libvorbis=1.3.7=h7b6447c_0
  - libxcb=1.16=hb9d3cd8_1
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=h4c95cb1_3
  - libzlib=1.3.1=h4ab18f5_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mistune=3.1.2=py312h06a4308_0
  - mpg123=1.32.6=h59595ed_0
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - nbclient=0.10.2=py312h06a4308_0
  - nbconvert=7.16.6=py312h06a4308_0
  - nbconvert-core=7.16.6=py312h06a4308_0
  - nbconvert-pandoc=7.16.6=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=py312h06a4308_0
  - nodejs=20.12.2=hb753e55_0
  - notebook=7.3.2=py312h06a4308_0
  - notebook-shim=0.2.4=py312h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.103=h593d115_0
  - openssl=3.3.1=hb9d3cd8_3
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.2=py312h06a4308_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py312h06a4308_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.3.7=py312h06a4308_0
  - ply=3.11=py312h06a4308_1
  - prometheus_client=0.21.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - pyqt=5.15.10=py312h6a678d5_1
  - pyqt5-sip=12.13.0=py312h5eee18b_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.5=h2ad013b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-json-logger=3.2.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - qt-main=5.15.8=h320f8da_24
  - qtconsole=5.6.1=py312h06a4308_0
  - qtpy=2.4.1=py312h06a4308_0
  - readline=8.2=h8228510_1
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.32.3=py312h06a4308_1
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.22.3=py312h4aa5aa6_0
  - send2trash=1.8.2=py312h06a4308_1
  - setuptools=78.1.0=pyhff2d567_0
  - sip=6.7.12=py312h6a678d5_1
  - six=1.17.0=py312h06a4308_0
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.4.0=py312h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py312h5eee18b_0
  - traitlets=5.14.3=py312h06a4308_0
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - urllib3=2.3.0=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.13=py312h06a4308_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxxf86vm=1.1.5=h4bc722e_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - contourpy==1.3.1
      - cxxfilt==0.3.0
      - cycler==0.12.1
      - fonttools==4.57.0
      - importlib-metadata==8.6.1
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - numpy==2.2.4
      - pandas==2.2.3
      - pillow==11.1.0
      - pyjwt==2.10.1
      - pyparsing==3.2.3
      - python-arango==8.0.0
      - pytz==2025.2
      - requests-toolbelt==1.0.0
      - seaborn==0.12.2
      - tzdata==2025.2
      - zipp==3.21.0
